### ISSUE TITLE
“Unknown error” with version 1.34

### ISSUE THREAD

**Issue by rusty1281** [standardnotes/standalone#10] opened 2021-06-05 17:52 UTC
Hello all,

I seem to have some sort of problem with the latest versions of sync/gateway/auth images. 

At the moment I am running 10 days old images (1.27.x) and it all runs just fine with desktop, mobile and self-hosted web version. 

Today I have update 3 images in question and updated the stack. No problem with the upgrade process but I got booted from my session on all 3 platforms. 

I have tried to log in with my current credentials but I kept getting wrong credentials error in the UI. 

Also, there was no way to make a new account as it resulted in “unknown error”. 

Nothing in the logs for the gateway, auth or the sync container (also not in the worker ones). 

I have tried to configure this new setup as a completely new stack with a new database but the result is the same. 

Need to point out that the database is an external MySQL instance but as I said it worked fine so far. 

Also, the fresh DB populates with fresh tables but as soon as I start to register (generating keys), the unknown error pops up. This happens with desktop client 3.7.1 and the latest web or iOS app. 

Reverting to the images from 10days ago I can make a fresh new instance (db) and register just fine as well as log back into my existing setup. 

I did notice there were some cleanups regarding ENV files but that didn’t make any difference because as I wrote a complete new setup with these modifications and a fresh db also results with the unknown error. 

Health check is OK in any case and there are no major problems from that standpoint that I have noticed. 

Any help on this matter would be greatly appreciate. 

Thanks!

**Comment by jonwsoto** [comment] 2021-06-08 19:32
I had a similar experience and the issue was the api gateway. They recently updated and seems to be working for me now.  The 1.15.4 version that was updated yesterday.

**Comment by karolsojko** [comment] 2021-06-09 07:24
Hey @rusty1281 can you update and check if it works now as @jonwsoto mentioned.

If not please provide us with the service versions you are running and a dump of logs during the request.

**Comment by rusty1281** [comment] 2021-06-09 08:00
> Hey @rusty1281 can you update and check if it works now as @jonwsoto mentioned.
> 
> If not please provide us with the service versions you are running and a dump of logs during the request.

Will do! Doing it right now and will post back on the matter. Tnx again!

**Comment by rusty1281** [comment] 2021-06-09 09:08
Unfortunately using the latest images I still get an unknown error. Here are the logs.

[_standardnotes_js_cache_1_logs.txt](https://github.com/standardnotes/standalone/files/6622493/_standardnotes_js_cache_1_logs.txt)
[_standardnotes_js_syncing-server-js-worker_1_logs.txt](https://github.com/standardnotes/standalone/files/6622494/_standardnotes_js_syncing-server-js-worker_1_logs.txt)
[_standardnotes_js_auth-worker_1_logs.txt](https://github.com/standardnotes/standalone/files/6622495/_standardnotes_js_auth-worker_1_logs.txt)
[_standardnotes_js_syncing-server-js_1_logs.txt](https://github.com/standardnotes/standalone/files/6622496/_standardnotes_js_syncing-server-js_1_logs.txt)
[_standardnotes_js_api-gateway_1_logs.txt](https://github.com/standardnotes/standalone/files/6622497/_standardnotes_js_api-gateway_1_logs.txt)
[_standardnotes_js_auth_1_logs.txt](https://github.com/standardnotes/standalone/files/6622499/_standardnotes_js_auth_1_logs.txt)

**Comment by karolsojko** [comment] 2021-06-09 10:54
I can't see any requests being made on neither API Gateway, Syncing Server or Auth. 

Can you open your dev console in the browser and paste the failing request here? Maybe it's not calling the server at all?

**Comment by rusty1281** [comment] 2021-06-09 11:18
> I can't see any requests being made on neither API Gateway, Syncing Server or Auth.
> 
> Can you open your dev console in the browser and paste the failing request here? Maybe it's not calling the server at all?

Well, these logs look the same now with 1.27.x version as well, and everything works. 

I will try and get this going again to force the error, but in the meantime, I had to revert back using the old images as I needed my stack up and running.

Will post back as soon as I simulate the setup again with fresh images and fresh DB.

**Comment by karolsojko** [comment] 2021-06-11 12:03
@rusty1281 would be great if you could share the versions of all services you are running. Just the sole version of the `syncing-server-js` (wether it's 1.27 or 1.34 won't do) . Keep in mind all of those services are interdependent so it's not recommended to change a version of just one service. For example: `auth:1.10.0` might not work with `syncing-server-js:1.34.1` but only with `syncing-server-js:1.35.0` and up. That's why we update the whole setup on a regular basis

**Comment by rusty1281** [comment] 2021-06-11 12:12
I am aware of this, and I have tested with the latest tag versions 2 days ago (not with the ones that were pushed 2h ago). So all 3 images have been updated (apart from redis that didnt needed a change).

Atm, the working versions that run just fine are

sync server - 1.27.0
auth - 1.7.0
api - 1.5.0

All images were downloaded on the 25th of May and those images work fine.

SQL side of things is being used as a separate container outside of this stack, but again, this is already in the format of the new "standalone" setup, and it does work ok. 

I did notice that you have pushed new images just a few hours ago. I will try this new stack again soon and report back.

Tnx for your effort on the matter and this whole solution, love it!

**Comment by karolsojko** [comment] 2021-06-11 12:21
Hmm are you experiencing this "Unknown error" in the browser? Any chances for a screenshot with what is in development "console" tab in the browser and "network" tab as well on the failing request?

**Comment by rusty1281** [comment] 2021-06-11 12:26
As soon as the stack starts (health check is OK), the tables get created, and then no matter what client I use (macOS version 3.8), iOS (latest), or the WebClient (also latest), I get booted from my existing session and present with the username/pass request.

If I try and enter it on any of my platforms I get an incorrect username/pass. The unknown error happens if I completely log out and then try to log in or try and create a new fresh account. This happens in the Generating Keys step, as the new account does get created in the DB, but as before with an existing account there is the "unknown error".

> Any chances for a screenshot with what is in the development "console" tab in the browser and "network" tab as well on the failing request?

I will get around and try and get this information when I start with a fresh stack later today or tomorrow.

**Comment by rusty1281** [comment] 2021-06-14 10:36
Still haven't looked into this as the weekend was busy. Will post back as soon as I test it out again.

**Comment by jonwsoto** [comment] 2021-06-15 03:45
Hey Rusty, I actually follow your blog and have learned a lot from you. Here is my experience so far after many tests. Take everything following with a grain of salt as I am only 2 months into my self hosting ventures and new to docker. Anywho I got it working and maybe this will trigger some thoughts to correct your problem. Forgive me if any terminology/jargon is not correct.

Initially I had a hard time creating a separate instance just for testing purposes to ensure it would all run properly with the default yaml settings. For some reason running a default stack instance would not allow me to connect and kept throwing an unknown error. I could not created a new user. I would review the developer dbug and see I would get connection refused. I noticed the same error when I would visit the designated domain from my nginx proxy manager. It would take me to a connection refused page. This was all despite getting OK on healthcheck. 

I realized that I was running my legacy syncserver with container port of 3000. I am not certain if this was the problem but the new instance also was using the same 3000 port. I was even using a separately defined exposed port thinking it would not matter. Anyways I am not to certain about docker networking but what I experimented with was editing the docker-compose.yaml and changed all the 3000 port references to a different port number. I did the same for the .env files, anywhere where the auth or sync server or anything was referencing port 3000. Anywhere I saw a 3000 I changed it lol.  My belief was that my nginx proxy was not able to know which container to access. Not sure if this is true but anyways I got the stack up and working. I was able to created a new user and sync with the self hosted web app without a problem. 

Next, I had to figure out how to transfer my data out of my baremetal mariadb to the stack mysql db. I failed exporting and re-importing, using the import folder prior to creating the stack, it was not taking it for some reason. How I resolved this was use the standard notes app to download the backup from my legacy instance to my desktop.

Then I created a new account on the standalone stack instance and then imported this backup after logging. Everything transferred, including my 2fa code, all my notes, and extensions. I did not have anything in filesafe so I am not sure if that would have been a problem. 

Anyways, now that I had it transferred over to this new instance and everything was in the stack mysql db. I created yet another instance to play around more. My goal was to figure out how to dump a containerized mysql database and move the dump to a new database in hopes to retain all my user accounts and passwords and all their data. 

I was able to use a container phpmyadmin to point to the exposed port on the mysqldb from the stack and dump the database to my desktop through phpmyadmin. I will go on a tangent here because a problem I encounter and noticed was that after each failed stack attempt, the .yaml file was written to created a new exposed port for the container mysql database. I had to keep changing what port the phpmyadmin would point towards in order to properly connect. I remedied this by binding a specific port with xxxx:3306 under the db ports line of the docker-compose.yaml

Anyways moving on. Prior to creating the 3rd instance of the standalone stack. I changed the mysql dump to dumpdb.sql and placed it into the import folder. I ran the new stack and it was able to import the mysqldb dump. It appeared to transfer everything and accept everything no problems, including the user names, passwords. Basically if I ever needed to recreate or transfer this, I would be able to dump the mysql and transfer it over pretty simply. My users would essentially just need to relog in and that's it. 

Since this venture, things have been updated. I was able to pull the latest images and update without any issues. 

I have learned a lot through this process and hope to help someone else. Hope this helps!

Other things I did was update the collation the db used as it was throwing errors it was using a deprecated collation. I used this:
   --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci

Errors I notice that I am not sure I should worry about or even know how to fix. 

Under cache container: 
# Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
# WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
# WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

Under db container:
[Warning] [Server] CA certificate ca.pem is self signed.
[Warning] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
[Warning] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.

**Comment by rusty1281** [comment] 2021-06-16 12:07
>Other things I did was update the collation the db used as it was throwing errors it was using a deprecated collation. I used this:

`--character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci`

Looking at the regular compose file, the DB collation is still UTF8_general_ci and that is the one I am using

Tnx for your feedback!

@karolsojko 
>Any chances for a screenshot with what is in the development "console" tab in the browser and "network" tab as well on the failing request?

I have just now tried a complete fresh stack on a NAS/Docker setup that has never had this setup before and a fresh empty DB with utf8_general_ci collation

I still get an error while trying to create a new user on a fresh instance using web app version 3.7.0

The images in use are:

- standardnotes/syncing-server-js:1.35.0
- standardnotes/api-gateway:1.17.0
- standardnotes/auth:1.10.0
- redis:latest

The MySQL is outside this stack but the DB has been created just fine with the initial 13 tables.

The requested images in the moment of error are included below.

Thank you again for looking into this!

<img width="1144" alt="Screenshot 2021-06-16 at 13 56 41" src="https://user-images.githubusercontent.com/5110408/122215835-021bb880-ceac-11eb-957e-aba91564ec34.png">
<img width="1145" alt="Screenshot 2021-06-16 at 13 58 59" src="https://user-images.githubusercontent.com/5110408/122215849-047e1280-ceac-11eb-9b9a-70fd517a45f1.png">
<img width="949" alt="Screenshot 2021-06-16 at 14 06 29" src="https://user-images.githubusercontent.com/5110408/122215883-0ea01100-ceac-11eb-87a2-babd9e67e497.png">

**Comment by mobitar** [comment] 2021-06-16 15:16
I don't believe you are allowed to access non-HTTPS resources from an HTTPS page. So if you are using our web app at app.standardnotes.org, you might not be able to connect to a local IP based server. Try using [ngrok](https://ngrok.com/) temporarily to create an HTTPS tunnel to your localhost to see if that's the cause.

**Comment by rusty1281** [comment] 2021-06-16 16:22
> I don't believe you are allowed to access non-HTTPS resources from an HTTPS page. So if you are using our web app at app.standardnotes.org, you might not be able to connect to a local IP based server. Try using ngrok temporarily to create an HTTPS tunnel to your localhost to see if that's the cause.

That was the problem yes. I do have it all on https, just not this demo one, considering I was using a self-hosted web app but indeed it was behind https. Pushing the whole setup behind ssl did the trick and import of DB backup (notes) did work just fine.

Now to test is the in place upgrade of my current setup will also work, as this was the initial problem, and there also everything is on https.

Guess we can consider this particular problem closed, if nothing else I will migrate to this working setup and see what happens.

Thank you all for your valuable input.

**Closed** 2021-06-16 16:31 UTC
Labels: help wanted

**Comment by rusty1281** [comment] 2021-06-16 18:01
Just wanted to say that I have tried to run on my existing host everything from scratch and again same problem. Looking at the logs some services are not bootin up on their "3000" ports and ofc the stack is not functional. No error just not completing the procedure.

That worked until a week ago.

On the second host, everything runs fine... not sure why but I need to cool my head 1st before I destory my monitor and revisit this another time.
